### ISSUE TITLE
1.21.1 Forge cant load the game with CurseForge or in the minecraft folder crashes before I can get in minecraft

### ISSUE THREAD

**Issue by AustinGreen8209** [CorgiTaco-MC/CorgiLib#60] opened 2024-12-25 18:05 UTC

**Comment by CorgiTaco** [comment] 2024-12-25 18:42
No details and no information given so closing this. I have zero way of knowing what the issue is or how to fix it. Please provide a latest.log and recreation steps, thanks!

**Comment by AustinGreen8209** [comment] 2024-12-25 18:46
I don't have the crash log, I just download Corgilib 1.21.1 any version. I downloaded it on Curseforge and It crashed, I put it in the Minecraft folder separate from Curseforge and crashed.

**Comment by CorgiTaco** [comment] 2024-12-25 18:49
@AustinGreen8209 why I said to provide a latest.log not a crash log

**Comment by AustinGreen8209** [comment] 2024-12-25 19:22
[20:31:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:31:33] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:31:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:31:33] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[20:31:33] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\carte\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\jre-legacy\windows-x64\jre-legacy
[20:31:33] [main/INFO] [FML]: Searching C:\Users\carte\AppData\Roaming\.minecraft\mods for mods
[20:31:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:31:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:31:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:31:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:31:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:31:34] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:31:34] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:31:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:31:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:31:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:31:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:31:34] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:31:35] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: AustinGreen8209
[20:31:36] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[20:31:36] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[20:31:36] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 324051936 bytes (309 MB) / 536870912 bytes (512 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 560.81' Renderer: 'NVIDIA GeForce RTX 4070 Ti SUPER/PCIe/SSE2'
[20:31:36] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[20:31:36] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[20:31:36] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[20:31:36] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[20:31:36] [Client thread/WARN] [FML]: Enabling removal of erroring Entities - USE AT YOUR OWN RISK
[20:31:36] [Client thread/WARN] [FML]: Enabling removal of erroring Tile Entities - USE AT YOUR OWN RISK
[20:31:36] [Client thread/INFO] [FML]: Searching C:\Users\carte\AppData\Roaming\.minecraft\mods for mods
[20:31:37] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[20:31:37] [Client thread/INFO] [FML]: FML has found a non-mod file GreedyCraft-1.35.2.118.1.zip in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[20:31:37] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at CLIENT
[20:31:37] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at SERVER
[20:31:37] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, Default Improved 1.12 - Storage Drawers Addon.zip, Default Improved 1.12 - Storage Drawers Extras Addon.zip, Default Improved PBR 1.12 - Biomes+O' Plenty.zip, Default Improved PBR 1.12 - Quark.zip, Default Improved PBR 1.12 Base Metals_thermalfoundation.zip, VanillaTweaks_r994246.zip, GreedyColors.zip
[20:31:37] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[20:31:37] [Client thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[20:31:37] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[20:31:37] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[20:31:37] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 8
[20:31:37] [Client thread/INFO] [FML]: Applying holder lookups
[20:31:37] [Client thread/INFO] [FML]: Holder lookups applied
[20:31:37] [Client thread/INFO] [FML]: Applying holder lookups
[20:31:37] [Client thread/INFO] [FML]: Holder lookups applied
[20:31:37] [Client thread/INFO] [FML]: Applying holder lookups
[20:31:37] [Client thread/INFO] [FML]: Holder lookups applied
[20:31:37] [Client thread/INFO] [FML]: Applying holder lookups
[20:31:37] [Client thread/INFO] [FML]: Holder lookups applied
[20:31:37] [Client thread/INFO] [FML]: Injecting itemstacks
[20:31:37] [Client thread/INFO] [FML]: Itemstack injection complete
[20:31:37] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[20:31:37] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[20:31:37] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:31:37] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[20:31:38] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[20:31:38] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 71769900 nanos
[20:31:39] [Client thread/INFO] [FML]: Max texture size: 16384
[20:31:40] [Client thread/INFO] [net.minecraft.client.renderer.texture.TextureMap]: Created: 1024x512 textures-atlas
[20:31:40] [Client thread/INFO] [FML]: Applying holder lookups
[20:31:40] [Client thread/INFO] [FML]: Holder lookups applied
[20:31:40] [Client thread/INFO] [FML]: Injecting itemstacks
[20:31:40] [Client thread/INFO] [FML]: Itemstack injection complete
[20:31:40] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[20:31:40] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[20:31:40] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: The following texture errors were found.
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: ==================================================
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:   DOMAIN minecraft
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: --------------------------------------------------
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:   domain minecraft is missing 2 textures
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:     domain minecraft has 3 locations:
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       resource pack at path C:\Users\carte\AppData\Roaming\.minecraft\resourcepacks\VanillaTweaks_r994246.zip
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       resource pack at path C:\Users\carte\AppData\Roaming\.minecraft\resourcepacks\GreedyColors.zip
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: -------------------------
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:     The missing resources for domain minecraft are:
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       textures/blocks/oak.png
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:       textures/blocks/furnace_front.png
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: -------------------------
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]:     No other errors exist for domain minecraft
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: ==================================================
[20:31:40] [Client thread/ERROR] [FML.TEXTURE_ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[20:31:53] [Client thread/INFO] [net.minecraft.world.storage.SaveFormatOld]: Deleting level New World
[20:31:53] [Client thread/INFO] [net.minecraft.world.storage.SaveFormatOld]: Attempt 1...
[20:31:57] [Client thread/INFO] [net.minecraft.client.Minecraft]: Stopping!
[20:31:57] [Client thread/INFO] [net.minecraft.client.audio.SoundManager]: SoundSystem shutting down...
[20:31:58] [Client thread/WARN] [net.minecraft.client.audio.SoundManager]: Author: Paul Lamb, www.paulscode.com


Im sorry I got no idea what im doing im just trying to play minecraft

**Comment by CorgiTaco** [comment] 2024-12-25 19:40
@AustinGreen8209 you're on mc 1.12 not 1.21?🤨

**Closed as not planned** 2024-12-25 19:40 UTC

**Comment by AustinGreen8209** [comment] 2024-12-25 20:03
![image](https://github.com/user-attachments/assets/8141fa69-3035-4226-81ea-73abf695cfd2)

![image](https://github.com/user-attachments/assets/c5ee8cc5-a38d-4732-a8e8-44e00cb713e4)

![image](https://github.com/user-attachments/assets/19dd0fcc-4a17-4895-92d0-0b118730ab58)


Idk what to do it says 1.21.1 on my end and all the other mods in the pack work on 1.21.1

**Comment by AustinGreen8209** [comment] 2024-12-25 20:19
I fixed it, I went to the logs on the minecraft appdata thing and just deleted everything tried it again and it worked idk how it worked though

**Comment by AustinGreen8209** [comment] 2024-12-25 20:22
it's doing it again now I don't know what happened the mod was by itself when It worked like 1 minute later it didn't work again Im so confused

**Comment by AustinGreen8209** [comment] 2024-12-25 20:24
ok I got it to work again idk how but now Enhanced Celestials is broken and is crashing my game, but it was corgilib
