### ISSUE TITLE
Prevents server shutdown when used alongside Create mod

### ISSUE THREAD

**Issue by simeonpfeiffer** [CorgiTaco-MC/CorgiLib#53] opened 2024-08-18 17:05 UTC
Minecraft 1.20.1
Fabric Loader 0.16.2 Launcher 1.0.1
Create 0.5.1f
Fabric API 0.92.2
Owo lib 0.11.2
CorgiLib 4.0.2.0

This minimal setup will prevent the server from shutting down after issuing the stop command. 

The console will freeze after these lines:

> [18:45:36] [Server thread/INFO]: Stopping the server
> [18:45:36] [Server thread/INFO]: Stopping server
> [18:45:36] [Server thread/INFO]: Saving players
> [18:45:36] [Server thread/INFO]: Saving worlds
> [18:45:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[name]'/minecraft:overworld
> [18:45:41] [Server thread/INFO]: ThreadedAnvilChunkStorage (name): All chunks are saved
> [18:45:41] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

The process will not terminate. There is no error message.

**Comment by Coolkc456** [comment] 2024-08-25 07:57
Came here because of this same issue as well! Can't use these mods together without killing the server which is risky.

**Comment by DumbXBoxAcct** [comment] 2024-09-13 05:23
Same here, server unload freezes after these lines:

[01:11:50] [Server thread/INFO]: Stopping the server
[01:11:50] [Server thread/INFO]: Stopping server
[01:11:50] [Server thread/INFO]: Saving players
[01:11:50] [Server thread/INFO]: Saving worlds
[01:11:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[01:11:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[01:11:50] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[01:11:51] [pool-2-thread-1/INFO]: Unloading server config for airhop

When using CorgiLib 1.20.1-4.0.3.2. with the following loaded:
 - fabric-server-mc.1.20.1-loader 0.16.4-launcher.1.0.1
 - Fabric API 0.92.2
 - ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
 - PuzzlesLib-v8.1.23-1.20.1-Fabric
 - AirHop-v8.0.2-1.20.1-Fabric

Substituting any one of these below for AirHop-v.8.0.2 also causes the issue:
- BarteringStation-v8.0.0-1.20.1-Fabric
- BetterTridents-v8.0.1-1.20.1-Fabric
- TradingPost-v8.0.2-1.20.1-Fabric

**Comment by Coolkc456** [comment] 2024-09-29 07:12
Any update on this? I really want to open a server but this issue is preventing me from doing so since I can't have proper restarts...

**Comment by simeonpfeiffer** [comment] 2024-09-29 07:14
I have removed all mods that require CorgiLib for the time being.

**Comment by Coolkc456** [comment] 2024-09-29 07:16
It's disappointing. I really wanted to use Oh The Biomes We've Gone as the worldgen but if this isn't fixed soon, I'll have to switch to something else.

**Comment by CorgiTaco** [comment] 2024-09-30 01:53
It should be fixed in the latest jar....

**Comment by Asterveila** [comment] 2024-09-30 06:55
When's the latest download gonna be available? i have the (as of writing this) latest ver from curse/modrinth, 4.0.3.2 and i'm having this same issue. Although i'm not using Create mod

**Comment by Coolkc456** [comment] 2024-10-16 05:38
Still having the issue as well with version 4.0.3.2.

**Comment by Coolkc456** [comment] 2024-11-06 00:46
Another person having the same issue but from Reddit: https://www.reddit.com/r/admincraft/comments/1gi9nn9/is_this_safe_server_not_turning_off_properly/?share_id=gtbjlojzt5QhTql9Yaq0W&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1

**Comment by Hinzy-Admin** [comment] 2024-11-10 19:56
> Another person having the same issue but from Reddit: https://www.reddit.com/r/admincraft/comments/1gi9nn9/is_this_safe_server_not_turning_off_properly/?share_id=gtbjlojzt5QhTql9Yaq0W&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1

this is me, now my server isnt saving at all when turning off, its getting stuck on saving worlds. 
[latest.log](https://github.com/user-attachments/files/17692866/latest.log)

**Comment by MimzyFang** [comment] 2024-11-17 21:43
reproduced the issue in a absolute minimal configuration
https://mclo.gs/BXxX5mm

List of mods:
Corgilib-Fabric-1.20.1-4.0.3.2.jar
create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
fabric-api-0.92.2+1.20.1.jar

fabric loader:
fabric-server-mc.1.20.1-loader.0.16.9-launcher.1.0.1.jar

**Comment by Coolkc456** [comment] 2024-12-02 23:09
Any update on this?

**Comment by Coolkc456** [comment] 2024-12-17 14:16
It's been 3 months since the developer has responded to this issue. I am really trying to be polite, but we're being left in the dark on if this bug is even being actively worked on and it's becoming increasingly frustrating. I have considered switching to a different world gen mod, but I've already done so much work on my world prior to discovering the issue and I really want to like this mod if I can run it properly. This bug is extremely inconvenient for me and a few others I've talked to about it. I'm pretty much begging for some sort of update to the situation. Perhaps after the holidays have passed? Thanks.

**Comment by MimzyFang** [comment] 2024-12-17 15:22
I'm putting a bounty on this whoever fixes it gets 100€ from me
PayPal or Revolut

**Comment by Hinzy-Admin** [comment] 2024-12-17 15:24
You could probably find out what's causing it using a java thread profiler pretty easily

**Comment by Coolkc456** [comment] 2024-12-17 15:26
Err... true, but I'm sure Corgi has rules against decompiling/modifying his code. Might wanna check with him for permission first. As frustrated as I am with the bug, it is his property.

**Comment by MimzyFang** [comment] 2024-12-17 20:24
> Err... true, but I'm sure Corgi has rules against decompiling/modifying his code. Might wanna check with him for permission first. As frustrated as I am with the bug, it is his property.

the code is fully available and under the [LGPL-3.0](https://github.com/CorgiTaco/CorgiLib/blob/1.20.X/LICENSE) there is no need to decompile it and anyone should be fine to modify it as long as they comply with the terms of the License

**Comment by CorgiTaco** [comment] 2024-12-17 21:49
@Coolkc456 if I was paid to work on these mods I would prioritize this but I've been unfortunately swamped with things outside of this issue. Secondly I've checked the issue out but couldn't find the root cause of what causes the server to hang. Thirdly anyone can fork and make a PR with the fix for this if they do find the issue. Or uploaded their own fix to curseforge/modrinth but they'd be silly doing that but it can be done bc of the license.

**Comment by CorgiTaco** [comment] 2024-12-18 08:59
I looked this over again and can't recreate the server stalling issue at all so I'm not sure how to go about profiling this. Someone with an already borked instance would need to use: https://visualvm.github.io/download.html and give me a screenshot of where it hangs

**Comment by Coolkc456** [comment] 2024-12-18 11:58
I've never used VisualVM before. I have reproduced the issue on a local host Fabric server. I'm not sure what part of VisualVM you need screenshots of, so please let me know if these screenshots are what you need. All screenshots are taken when the server refuses to stop.

Minecraft profile used for testing...
Fabric version: 1.20.1-0.16.8
Mods:
fabric-api-0.92.2+1.20.1
CorgiLib-Fabric-1.20.1-4.0.3.2
Oh-The-Biomes-Weve-Gone-Fabric-1.4.4
Oh-The-Trees-Youll-Grow-fabric-1.20.1-1.3.2
TerraBlender-fabric-1.20.1-3.0.1.7
owo-lib-0.11.2+1.20
geckolib-fabric-1.20.1-4.4.9
create-fabric-0.5.1-f-build.1417+mc1.20.1
![VisualVM1](https://github.com/user-attachments/assets/ded092e7-7b57-4d6f-9fa7-71c9103e35e9)
![VisualVM2](https://github.com/user-attachments/assets/1db46b51-70dc-45b2-8e33-164e940f1687)
![VisualVM3](https://github.com/user-attachments/assets/95cf6d79-536b-427c-b6ba-8dfe69b36ec0)
![VisualVM4](https://github.com/user-attachments/assets/c9dec410-bada-4d9f-a1ab-4fc2fa2585f5)
![VisualVM5](https://github.com/user-attachments/assets/36f35aae-7f30-4643-88bb-c353a13e7930)
![VisualVM6](https://github.com/user-attachments/assets/203fb23b-92ce-4fec-ba00-197645afb6bb)

**Comment by CorgiTaco** [comment] 2024-12-18 17:42
@Coolkc456 i'd need the sampler tab specifically, expand the "Config file watcher"? Bc that looks like a culprit

**Comment by Coolkc456** [comment] 2024-12-18 17:57
@CorgiTaco Is this what you mean?
![VisualVM7](https://github.com/user-attachments/assets/6ca753a9-f971-475b-8ee4-6f2a1c145032)

**Comment by CorgiTaco** [comment] 2024-12-18 18:03
yes! @Coolkc456 

And nothing seems wrong so what's is making it hang.... hmmm

**Comment by Coolkc456** [comment] 2024-12-18 18:08
@CorgiTaco Would it help if I zipped up my entire profile and linked a download to it to see if you can reproduce it with the same profile?

**Comment by CorgiTaco** [comment] 2024-12-18 18:08
@Coolkc456 yes

**Comment by Coolkc456** [comment] 2024-12-18 18:17
@CorgiTaco All you should have to do is double click the start.bat to launch the server and then type stop in the window to reproduce the error, at least on my end.

https://www.dropbox.com/scl/fi/xj5exg9sdzjil3xgnt42r/CorgiLib-Stall-Test-Profile.zip?rlkey=klp5rtpcj71gtaj8oyaup3f72&st=5t2znavq&dl=0

**Comment by CorgiTaco** [comment] 2024-12-18 18:32
@Coolkc456 yeah i genuinely do not know what's going on here lol

**Comment by CorgiTaco** [comment] 2024-12-18 18:55
Found the issue, related to: https://github.com/TheElectronWill/night-config/issues/187

**Closed as completed** 2024-12-18 18:58 UTC

**Comment by CorgiTaco** [comment] 2024-12-18 19:01
@Coolkc456 @simeonpfeiffer @Fauli1221 @Hinzy-Admin New version up with the fix

**Comment by MimzyFang** [comment] 2024-12-18 19:10
Cool

**Comment by Coolkc456** [comment] 2024-12-18 19:10
Thank you so much! Works like a charm!

**Comment by MimzyFang** [comment] 2024-12-18 19:15
> @Coolkc456 @simeonpfeiffer @Fauli1221 @Hinzy-Admin New version up with the fix

@CorgiTaco you can message me on discord at the.birb.horse or on mastodon at [@fauli1221@hooves.social](https://hooves.social/@fauli1221) to claim the bounty

thank you so much for the fix
